
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Expose to host
      - "3000:3000"  # http backend
      - "3443:3443"  # https backend
    environment:
      - NODE_ENV=production
    networks:
      - transcendence_net
    volumes:
      - ./db.sqlite:/workspaces/ft_transcendence/db.sqlite
    healthcheck:
      test: ["CMD", "/workspaces/ft_transcendence/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


networks:
  transcendence_net:
    driver: bridge

# volumes:
  # sqlite: